#!/usr/bin/env bash
# Extract the "Build time autogenerated kernel key" certificate, which signed
# the Debian modules, from a Debian arm64 vmlinuz (uncompressed Image).
#
# Usage: extract-debian-kernel-cert.sh <vmlinuz> <out.pem>
set -euo pipefail
python3 - "$1" "$2" <<'PY'
import re, subprocess, sys
d = open(sys.argv[1], 'rb').read()
for m in re.finditer(rb'\x30\x82(..)\x30\x82', d, re.S):
    der = d[m.start():m.start() + int.from_bytes(m.group(1), 'big') + 4]
    r = subprocess.run(['openssl', 'x509', '-inform', 'DER', '-noout', '-subject'],
                       input=der, capture_output=True)
    if r.returncode == 0 and b'Build time autogenerated kernel key' in r.stdout:
        pem = subprocess.run(['openssl', 'x509', '-inform', 'DER'], input=der,
                             capture_output=True, check=True).stdout
        open(sys.argv[2], 'wb').write(pem)
        sys.exit(0)
sys.exit('certificate not found')
PY
openssl x509 -in "$2" -noout -subject -fingerprint
